name: Remote SSH
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 104.251.211.216
        username: root
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /root/FiveM/server/txData/PlumeESXLegacy_7C9EBA.base/resources
          rm -r /root/FiveM/server/txData/PlumeESXLegacy_7C9EBA.base/cache
          git pull https://${{secrets.TOKEN}}@github.com/FlagshipDev/despiadadosResources.git
